# Generated by Django 4.0 on 2021-12-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название точки')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Список точек',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя работник')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Список работников',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Посещение')),
                ('coordinates', models.TextField(verbose_name='Координаты')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='api.store', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Список посещений',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='api.worker', verbose_name='Работник'),
        ),
    ]
